### ISSUE TITLE
Shouldn't 'make plot' in README be 'make run' instead?

### ISSUE THREAD

**Issue by tbdk** [guillaumesalagnac/memory-mountain#1]
Under "Usage" in the README.md file, it says: "Just type 'make plot' and enjoy the show. But this requires that the data file has already been generated. Maybe it would make more sense to write, first to type "make run" and then "make plot", as I believe "make run" does exactly what's described in the " Running an experiment" section?

**Comment by guillaumesalagnac** [comment]
I sugest look at the makefile itself: `make plot` does have a dependency on `${DATAFILE}`. In other words, typing `make run` and then `make plot` will have exactly the same effect as typing just `make plot`
